export const products = [
    {
        id: 1,
        type: 'almonds',
        name: 'Almonds',
        price: 12.99,
        image: '/almonds.jpg',
        rating: 5,
    },
    {
        id: 2,
        type: 'walnuts',
        name: 'Walnuts',
        price: 10.99,
        image: '/walnuts.jpg',
        rating: 5,
    },
    {
        id: 3,
        type: 'pecans',
        name: 'Pecans',
        price: 14.99,
        image: '/pecans.jpg',
        rating: 4.5,
    },
    {
        id: 4,
        type: 'hazelnuts',
        name: 'Hazelnuts',
        price: 13.49,
        image: '/hazelnuts.jpg',
        rating: 4.5,
    },
    {
        id: 5,
        type: 'pistachios',
        name: 'Pistachios',
        price: 16.99,
        image: '/pistachios.jpg',
        rating: 4,
    },
    {
        id: 6,
        type: 'cashews',
        name: 'Cashews',
        price: 15.99,
        image: '/cashews.jpg',
        rating: 5,
    },
    {
        id: 7,
        type: 'macadamia',
        name: 'Macadamia Nuts',
        price: 22.99,
        image: '/macadamia.jpg',
        rating: 4,
    },
    {
        id: 8,
        type: 'brazil_nuts',
        name: 'Brazil Nuts',
        price: 17.99,
        image: '/brazil_nuts.jpg',
        rating: 4.5,
    },
    {
        id: 9,
        type: 'pine_nuts',
        name: 'Pine Nuts',
        price: 21.99,
        image: '/pine_nuts.jpg',
        rating: 4.5,
    },
    {
        id: 10,
        type: 'peanuts',
        name: 'Peanuts',
        price: 6.99,
        image: '/peanuts.jpg',
        rating: 4,
    },
    {
        id: 11,
        type: 'mixed_nuts',
        name: 'Mixed Nuts',
        price: 19.99,
        image: '/mixed_nuts.jpg',
        rating: 4.5,
    },
    {
        id: 12,
        type: 'sunflower_seeds',
        name: 'Sunflower Seeds',
        price: 5.99,
        image: '/sunflower_seeds.jpg',
        rating: 4.5,
    },
];
